config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'

  
  resources :articles do
    resources :comments
    get 'admin_comments', to: "comments#admin_index"
  end
  
  resources :blocked_users
  resources :friendships
  resources :categories
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  scope "/accounts" do
    resources :users
  end

  root 'pages#home'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user   
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :create, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.paginate(page: params[:page], per_page: 10)
  end

  def admin_index
     @comments = Comment.paginate(page: params[:page], per_page: 10)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comments = Comment.paginate(page: params[:page], per_page: 5)
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(username: current_user.username, user_id: current_user.id )
    @comment.article_id = Article.find(params[:article_id]).id
    @comment.body = params[:body] 
   
    if @comment.save
      flash[:notice] = 'Comment was successfully created.'
      redirect_to article_comment_path(@article, @comment)
    else
      flash[:notice] = "Error creating comment: #{@comment.errors}"
      render "new"
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    flash[:danger] = "Comment was successfully deleted"

    redirect_to article_path(@article)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
     @comment = Comment.find(params[:id])
    end
    
    def set_article
      @article = Article.find(params[:article_id])
    end
   
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:username, :body, :article_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for :comment, :url => article_comments_path(params[:article_id]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :comment %>
      </div>
      <div class="col-sm-8">
        <%= hidden_field_tag :username, current_user.username %>
        <%= hidden_field_tag :article_id, @comment.article_id %>
        <%= hidden_field_tag :user_id, current_user.id %>
        <%= text_field_tag :body, @comment.body, class: "form-control", placeholder: "Comment goes here"%>
      </div>
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Body</th>
      <th>Article</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.username %></td>
        <td><%= comment.body %></td>
        <td><%= comment.article %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', article_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @comment.username %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_article_comment_path(params[:article_id], params[:id]) %> |
<%= link_to 'Back', article_comments_path %>