config/routes.rb
Rails.application.routes.draw do

  get 'pages/about'

  
  resources :articles do
    resources :comments
    get 'admin_comments', to: "comments#admin_index"
  end
  
  resources :blocked_users
  resources :friendships
  resources :categories
  
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  scope "/accounts" do
    resources :users
  end

  root 'pages#home'

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"    
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :destroy]

  # GET /friendships
  # GET /friendships.json
  def index
    @friendships = Friendship.all
    @user = current_user
  end

  # GET /friendships/1
  # GET /friendships/1.json
  def show
  end

  # GET /friendships/new
  def new
    @friendship = Friendship.new

  end

  # GET /friendships/1/edit
  def edit
  end

  # POST /friendships
  # POST /friendships.json
  def create
    @friend = User.find(params[:friend_id])
      @friendship = current_user.friendships.build( user_id: current_user.id, friend_id: params[:friend_id], friend_name: @friend.username, user_name: current_user.username, approved: "false")
      if @friendship.save
        flash[:notice] = "Friend request sent."
        redirect_to :back
      else
        flash[:danger] = "Unable to request friendship."
        redirect_to :back
      end
  end

  # PATCH/PUT /friendships/1
  # PATCH/PUT /friendships/1.json
  def update
    @friendship = Friendship.find(params[:id])
    @friendship.update(approved: true)
      if @friendship.save
        flash[:notice] = "Successfully confirmed friend!"
        redirect_to root_url
      else
        flash[:danger] = "Sorry! Could not confirm friend!"
        redirect_to root_url
      end
  end

  # DELETE /friendships/1
  # DELETE /friendships/1.json
  def destroy
    @friendship.destroy
    flash[:notice] = "Friendship successfully removed."
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :approved, :friend_name, :user_name)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :approved %><br>
    <%= f.check_box :approved %>
  </div>
  <div class="field">
    <%= f.label :friend_name %><br>
    <%= f.text_field :friend_name %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<div align="center">
  <h1>Listing <%= @user.username %>'s Friendships</h1>
  <div>
    <%= link_to gravatar_for(@user), user_path(@user) %>
  </div>
  
  <table>
    <thead>
      <tr>
        <th>Friend</th>
        <th></th>
        <th>Confirmed</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @friendships.each do |friendship| %>
          <tr>
            <% if friendship.friend_id == current_user.id  %>
              <td><%= friendship.user_name %></td>
            <% else %>  
              <td><%= friendship.friend_name %></td>
            <% end %>
            <td></td>
            <td><%= friendship.approved %></td>
          <% if friendship.approved %>
            <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>
          <% else %>
            <% if (current_user.id != friendship.user_id) && (current_user != friendship.friend_id) %>
              <td><%= link_to "Accept", friendship, :method => :put,  class: "btn btn-xs btn-primary" %></td>
              <td><%= link_to "Decline", friendship, :method => :delete, class: "btn btn-xs btn-warning" %></td>
            <% end %>
          <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'All users', users_path, class: "btn btn-xs btn-success" %>
</div>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @friendship.approved %>
</p>

<p>
  <strong>Friend name:</strong>
  <%= @friendship.friend_name %>
</p>

<p>
  <strong>User name:</strong>
  <%= @friendship.user_name %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>